let state;
const byId = (id) => document.getElementById(id);
const message = (text, error = false) => { const node = byId('message'); node.textContent = text; node.style.color = error ? '#a63b32' : '#166245'; };
const escape = (value) => String(value).replace(/[&<>'"]/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));
const option = (value, label) => `<option value="${escape(value)}">${escape(label)}</option>`;
async function load() { try { state = await fetch('/api/state').then(response => response.json()); render(); const incoming = (await fetch('/api/approval-requests').then(response => response.ok ? response.json() : [])) || []; byId('incoming-approvals').innerHTML = incoming.length ? incoming.map(request => `<article class="event"><strong>${escape(request.target_pcid)}</strong><br><small>${escape(request.request_id)}</small><br><button data-approve="${escape(request.request_id)}">Approve exact request locally</button></article>`).join('') : '<p>No pending local requests.</p>'; document.querySelectorAll('[data-approve]').forEach(button => button.addEventListener('click', async () => { const response = await fetch(`/api/approval-requests/${button.dataset.approve}/approve`, {method:'POST'}); const result = await response.json(); if (!response.ok) { message(result.error, true); return; } message('Approved exact record is durable.'); await load(); })); } catch (error) { message(`Page load failed: ${error.message}`, true); } }
function member(id) { return state.members.find(item => item.id === id); }
function area(id) { return state.areas.find(item => item.id === id).name; }
function render() {
  byId('tools').innerHTML = state.tools.map(tool => `<article class="tool ${tool.safetyHold ? 'hold' : ''}"><h3>${escape(tool.name)}</h3><p>${escape(area(tool.areaId))}</p><p class="status">${escape(tool.safetyHold ? 'Safety hold — unavailable' : tool.activeLoan ? `Loaned to ${member(tool.activeLoan.memberId).initials} until ${new Date(tool.activeLoan.dueAt).toLocaleString()}${tool.activeLoan.termsComplete ? '' : ' — accepted terms unavailable'}` : tool.condition)}</p><p>${tool.offSiteLoan ? 'Off-site loan eligible under area rules.' : 'In-space use only.'}</p><p>${(tool.observations || []).length} recorded observation(s).</p></article>`).join('');
  byId('policies').innerHTML = state.areas.map(item => `<article class="tool"><h3>${escape(item.name)}</h3><p class="status">Current policy ${escape(item.policyVersion)}</p><p>${escape(item.policy)}</p><p><small>Authority delegated by ${escape(item.delegatedBy)}.</small></p></article>`).join('');
  byId('authorities').innerHTML = state.authorities.map(authority => `<article class="tool"><h3>${escape(member(authority.memberId).name)}</h3><p>${escape(area(authority.areaId))} steward</p><p>${authority.scopes.map(escape).join(' · ')}</p><p><small>Recognized by ${escape(authority.recognizedBy)}; review by ${escape(authority.reviewAt)}.</small></p></article>`).join('');
  const members = state.members.map(item => option(item.id, `${item.name} (${item.initials})`)).join('');
  byId('access-member').innerHTML = members;
  renderEligibility();
  const evidence = state.tools.flatMap(tool => (tool.observations || []).map(observation => ({...observation, toolName: tool.name}))).sort((left, right) => new Date(right.createdAt) - new Date(left.createdAt));
  byId('timeline').innerHTML = evidence.length ? evidence.map(event => `<article class="event"><strong>${escape(event.toolName)}</strong> — ${escape(member(event.reporterId)?.name || event.reporterId)}<br>${escape(event.text)}<br><small>${new Date(event.createdAt).toLocaleString()}</small></article>`).join('') : '<p>No projected observations recorded yet.</p>';
}
function renderEligibility() {
  const memberID = byId('access-member').value;
  const viewer = member(memberID);
  const qualifications = state.qualifications.filter(item => item.memberId === memberID);
  byId('qualification-summary').textContent = qualifications.length ? `${viewer.name} has ${qualifications.length} currently accepted area qualification(s).` : `${viewer.name} has no currently accepted area qualifications.`;
  byId('eligibility').innerHTML = state.tools.map(tool => {
    const qualification = qualifications.find(item => item.areaId === tool.areaId && item.scope === tool.requiredQualification && item.status === 'accepted');
    const eligible = Boolean(qualification) && !tool.safetyHold;
    const required = tool.requiredQualification.replaceAll('-', ' ');
    const reason = tool.safetyHold ? 'This tool is on a safety hold pending area inspection.' : qualification ? `Eligible through the ${required} qualification issued by ${member(qualification.issuedBy).name}.` : `Not currently eligible: this requires an accepted ${required} qualification.`;
    return `<article class="tool ${eligible ? '' : 'hold'}"><h3>${escape(tool.name)}</h3><p class="status">${eligible ? 'Currently eligible' : 'Not currently eligible'}</p><p>${escape(reason)}</p><p><small>${tool.offSiteLoan ? 'Off-site lending is separately subject to current area terms.' : 'In-space use only.'}</small></p></article>`;
  }).join('');
}
byId('record-ingress-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const records = byId('signed-records').value.split(/\s+/).filter(Boolean); const response = await fetch('/api/records', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify({records})}); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); event.target.reset(); await load(); message('Exact signed record bytes retained; projection changed only when local recognition permits it.'); } catch (error) { message(error.message, true); } });
let pendingApproval;
async function pollApproval() { if (!pendingApproval || pendingApproval.state !== 'pending') return; const response = await fetch(`${pendingApproval.origin}/api/approval-requests/${pendingApproval.request_id}?token=${encodeURIComponent(pendingApproval.approval_token)}`); const result = await response.json(); if (!response.ok) { message(result.error, true); return; } pendingApproval = {...result, origin: pendingApproval.origin}; if (result.state === 'approved') { const ingress = await fetch('/api/records', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({records:[result.signed_record_base64]})}); const accepted = await ingress.json(); if (!ingress.ok) { message(accepted.error, true); return; } byId('approval-status').textContent = 'Participant-approved exact record received and independently retained by this terminal.'; await load(); return; } if (result.state === 'expired') { byId('approval-status').textContent = 'Unsigned request expired without a participant promise.'; return; } setTimeout(pollApproval, 750); }
byId('approval-request-form').addEventListener('submit', async (event) => { event.preventDefault(); try { const target = new URL(byId('approval-target').value); if (!['https:','http:'].includes(target.protocol) || (target.protocol === 'http:' && !['127.0.0.1','localhost','[::1]'].includes(target.hostname)) || target.username || target.password || target.hash) throw new Error('target must be HTTPS or loopback HTTP without credentials or fragment'); const payload = new TextEncoder().encode(JSON.stringify({observation: byId('approval-observation').value, tool_id: byId('approval-tool').value})); const response = await fetch(`${target.origin}/api/approval-requests`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({target_pcid:'bafkreifhodcald6kzib36rzeji27hnqjdkeycibnkcigcsz7mzejz6obiy', payload_base64:btoa(String.fromCharCode(...payload))})}); pendingApproval = await response.json(); pendingApproval.origin = target.origin; if (!response.ok) throw new Error(pendingApproval.error); byId('approval-status').textContent = `Unsigned request ${pendingApproval.request_id} is pending; poll token retained by this terminal.`; byId('approval-approve').hidden = target.origin !== location.origin; setTimeout(pollApproval, 750); } catch (error) { message(error.message, true); } });
byId('approval-approve').addEventListener('click', async () => { if (!pendingApproval) return; const response = await fetch(`/api/approval-requests/${pendingApproval.request_id}/approve`, {method:'POST'}); const result = await response.json(); if (!response.ok) { message(result.error, true); return; } pendingApproval = result; byId('approval-status').textContent = 'Approved locally; exact signed record is now durable evidence.'; byId('approval-approve').hidden = true; await load(); });
byId('access-member').addEventListener('change', renderEligibility);
load();
