package web

import (
	"strings"
	"testing"
)

func TestEmbeddedIndexIncludesOperationalWorkflowSections(t *testing.T) {
	index := string(MustRead("index.html"))
	required := []string{
		"workspace-status",
		"mode-rail",
		"mode-review",
		"mode-author",
		"workspace-summary",
		"create-details",
		"browse-details",
		"Review",
		"Author",
		"Operate",
		"Create",
		"Browse Collections",
		"Create Place",
		"Create Resource",
		"Live Draft Studio",
		"editor-status-cards",
		"editor-focus-writing",
		"editor-collab-details",
		"editor-lifecycle-details",
		"editor-support-details",
		"Writing Surface",
		"Primary Flow",
		"focus-drafts",
		"Current Record",
		"Review Queue",
		"review-lane-drafts",
		"review-lane-hotspots",
		"review-lane-search",
		"draft-review",
		"detail-primary",
		"search-preset-drafts",
		"search-advanced",
		"search-clear",
		"search-debug",
		"Operate From Current Record",
		"operate-choose-run",
		"operate-choose-evidence",
		"operate-choose-approve",
		"operate-run-details",
		"operate-evidence-details",
		"operate-approval-details",
		"operate-context",
		"operate-run-current",
		"run-item-select",
		"evidence-run-select",
		"approval-target-select",
		"resource-place-select",
		"detail-timeline",
		"detail-review",
		"search-kind",
		"search-status",
		"search-outcome",
		"search-place-select",
		"search-resource-select",
		"search-responsibility-select",
		"Manual ID filters",
		"Manual ID overrides and extra linked IDs",
		"Runs",
		"receiving_check",
		"inventory_audit",
		"Log Work Performed",
		"Capture Review Decision",
		"Attach Evidence",
		"Draft Item",
		"What checklist or procedure is this work based on?",
		"Which record is under review?",
		"Review draft items",
		"Draft queue",
		"Problem hotspots",
		"Known record search",
		"Save Run",
		"Save Evidence",
		"Save Decision",
		"Writing context",
		"Revision decisions",
	}
	for _, marker := range required {
		if !strings.Contains(index, marker) {
			t.Fatalf("embedded index missing %q", marker)
		}
	}
	reviewIndex := strings.Index(index, `workspace workspace-review`)
	createIndex := strings.Index(index, `workspace workspace-create`)
	if reviewIndex == -1 || createIndex == -1 || reviewIndex > createIndex {
		t.Fatalf("embedded index does not keep review ahead of create")
	}
}

func TestEmbeddedAppIncludesLiveDraftWorkflowHooks(t *testing.T) {
	app := string(MustRead("app.js"))
	required := []string{
		"editor-item-id",
		"/api/items/${editorState.itemID}/live",
		"/api/items/${itemID}/live/socket",
		"startLiveTransport",
		"connectLiveSocket",
		"sendLiveSocketUpdate",
		"scheduleLiveReconnect",
		"editor-snapshot",
		"renderPlaces",
		"renderSearchResults",
		"renderProblemReview",
		"getSearchFilters",
		"buildSearchParams",
		"refreshActionCatalog",
		"renderApprovalTargetOptions",
		"applyContextDefaults",
		"startRunFromContext",
		"startEvidenceFromRun",
		"startApprovalFromContext",
		"renderDetailPrimary",
		"makePrimaryActionButton",
		"setActiveMode",
		"setReviewLane",
		"openOperateStage",
		"focusMode",
		"renderEditorStatusCards",
		"renderDraftQueue",
		"renderOperateContext",
		"triggerOperateContext",
		"runPresetSearch",
		"syncSearchSelectAndOverride",
		"hasAdvancedSearchFilters",
		"workspace-status",
		"setWorkspaceStatus",
		"clearSearch",
		"makeActionButton",
		"/api/problem-review",
		"inspectRecord",
		"renderDetailTimeline",
		"renderDetailReview",
		"detailStats",
		"runSearch",
		"Related runs",
		"related_runs",
		"Receiving history",
		"Receiving context review",
		"Receiving review",
		"receivingRunEntries",
		"receivingEvidenceEntries",
		"receivingContextEntries",
		"Inventory count history",
		"Inventory discrepancy",
		"inventoryAuditEntries",
		"inventoryContextEntries",
		"formatEvidenceFacts",
		"Linked runs",
		"detail-json",
		"Search receiving here",
		"Search counts here",
		"Search problems here",
		"Record run for this item",
		"Add evidence to this run",
		"Approve this run",
		"Review hotspots",
		"Next Step",
		"Continue draft",
		"problem-focused",
		"participant_id",
		"safeParticipantStorage",
		"createMemoryStorage",
		"createParticipantID",
		"randomUUID",
		"liveSocketURL",
		"runHandled",
	}
	for _, marker := range required {
		if !strings.Contains(app, marker) {
			t.Fatalf("embedded app missing %q", marker)
		}
	}
}
